services:
  postgres:
    image: sjksingh/pg16-extended-orioledb:latest 
    container_name: pg16-extended-orioledb
    command:
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_PASSWORD: manager
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init-scripts:/docker-entrypoint-initdb.d
